config/routes.rb
DoorkeeperDeviseClient::Application.routes.draw do

  match 'explore/:api' => 'api#explore', :as => :explore_api
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable

  def self.find_or_create_for_doorkeeper_oauth(oauth_data)
    User.find_or_initialize_by_doorkeeper_uid(oauth_data.uid).tap do |user|
      user.email = oauth_data.info.email
    end
  end

  def update_doorkeeper_credentials(oauth_data)
    self.doorkeeper_access_token = oauth_data.credentials.token
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json

  def explore
    @json = doorkeeper_access_token.get("api/v1/#{params[:api]}").parsed
    respond_with @json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def doorkeeper_oauth_client
    @client ||= OAuth2::Client.new(DOORKEEPER_APP_ID, DOORKEEPER_APP_SECRET, :site => DOORKEEPER_APP_URL)
  end

  def doorkeeper_access_token
    @token ||= OAuth2::AccessToken.new(doorkeeper_oauth_client, current_user.doorkeeper_access_token) if current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def doorkeeper
    oauth_data = request.env["omniauth.auth"]
    @user = User.find_or_create_for_doorkeeper_oauth(oauth_data)
    @user.update_doorkeeper_credentials(oauth_data)
    @user.save

    sign_in_and_redirect @user
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%section
  .row
    .span16
      - unless signed_in?
        %h3 Sign in first to explore the provider's API
        %p= link_to "Sign in with OAuth 2 provider", user_omniauth_authorize_path(:doorkeeper), :class => "btn primary"
      - else
        %h2 Explore the api
        .well
          = link_to "My Credentials", explore_api_path(:me, :format => :json), :class => "btn", "data-explore" => []
          = link_to "Profiles", explore_api_path(:profiles, :format => :json), :class => "btn", "data-explore" => []
          = link_to "Sign out", destroy_user_session_path, :class => "btn primary"
          You are logged in as
          = current_user.email

        %p
          %pre#display-json
            Select one of the api methods above

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Doorkeeper Oauth Client (Devise + Omniauth)
    = stylesheet_link_tag    "http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css"
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  %body
    .topbar
      .fill
        .container
          = link_to "Doorkeeper Oauth Client (Devise + Omniauith)", root_path, :class => "brand"
    .container
      = yield
    = javascript_include_tag "application"
    = javascript_include_tag "http://twitter.github.com/bootstrap/1.4.0/bootstrap-buttons.min.js"